const productList = [
    {
        id_product: 1,
        category: "nacional",
        fk_idcategorys: 1,
        name_product: "Flamengo 2023/2024",
        price: 349.99,
        image: "images/Camisa-fla-2023.webp",
        id_categorys: 6,
        name_categorys: "Clubes europeus",
        selected: false,
    },
    {
        id_product: 2,
        category: "nacional",
        fk_idcategorys: 1,
        name_product: "Flamengo 2023/2024",
        price: 349.99,
        image: "images/Camisa-fla-2023.webp",
        id_categorys: 2,
        name_categorys: "Seleções",
        selected: false,
    },
    {
        id_product: 3,
        category: "nacional",
        fk_idcategorys: 1,
        name_product: "Flamengo 2023/2024",
        price: 349.99,
        image: "images/Camisa-fla-2023.webp",
        id_categorys: 3,
        name_categorys: "Campeões da Libertadores",
        selected: false,
    },
    {
        id_product: 4,
        category: "nacional",
        fk_idcategorys: 1,
        name_product: "Flamengo 2023/2024",
        price: 349.99,
        image: "images/Camisa-fla-2023.webp",
        id_categorys: 4,
        name_categorys: "Campeões da Champions",
        selected: false,
    },
    {
        id_product: 5,
        category: "nacional",
        fk_idcategorys: 1,
        name_product: "Flamengo 2023/2024",
        price: 349.99,
        image: "images/Camisa-fla-2023.webp",
        id_categorys: 5,
        name_categorys: "Clubes Brasileiros",
        selected: false,
    },
    {
        id_product: 6,
        category: "nacional",
        fk_idcategorys: 1,
        name_product: "Flamengo 2023/2024",
        price: 349.99,
        image: "images/Camisa-fla-2023.webp",
        id_categorys: 5,
        name_categorys: "Clubes Brasileiros",
        selected: false,
    },
    {
        id_product: 7,
        category: "nacional",
        fk_idcategorys: 1,
        name_product: "Flamengo 2023/2024",
        price: 349.99,
        image: "images/Camisa-fla-2023.webp",
        id_categorys: 6,
        name_categorys: "Clubes europeus",
        selected: false,
    },
    {
        id_product: 8,
        category: "nacional",
        fk_idcategorys: 1,
        name_product: "Flamengo 2023/2024",
        price: 349.99,
        image: "images/Camisa-fla-2023.webp",
        id_categorys: 7,
        name_categorys: "Seleções copa 2022",
        selected: false,
    },
    {
        id_product: 9,
        category: "nacional",
        fk_idcategorys: 1,
        name_product: "Flamengo 2023/2024",
        price: 349.99,
        image: "images/Camisa-fla-2023.webp",
        id_categorys: 8,
        name_categorys: "Mundial de clubes",
        selected: false,
    },
];

export default productList;